name: Release

on:
  push:
    branches:
      - master

jobs:
  build-on-win:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: run build
        run: npm run build:release
      - name: do package
        run: |
          npm run release